let tok=localStorage.zd||'';const $=s=>document.querySelector(s);function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='courses')loadCourses();if(id==='books')loadBooks();if(id==='account')account();if(id==='admin')admin();}
async function api(u,o={}){o.headers={...(o.headers||{}),'Content-Type':'application/json'};if(tok)o.headers.Authorization='Bearer '+tok;let r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error);return d}
async function loadCourses(){let f=$('#cfac')?.value.trim(),d=await api('/api/courses'+(f?'?faculty='+encodeURIComponent(f):''));$('#coursesBox').innerHTML=d.courses.length?d.courses.map(c=>`<div class="card"><small>${c.faculty}${c.department?' • '+c.department:''}</small><h3>${c.title}</h3><p>${c.description}</p><p>استاد: ${c.teacher||'—'} | درسونه: ${c.lessons||0}</p><b>${c.price?c.price+' AFN':'وړیا'}</b><br><button class="primary" onclick="access('${c.id}')">درس وګوره</button></div>`).join(''):'کورس ونه موندل شو.'}
async function loadBooks(){let d=await api('/api/books');$('#booksBox').innerHTML=d.books.length?d.books.map(b=>`<div class="card"><small>${b.faculty}</small><h3>📚 ${b.title}</h3><p>${b.description||''}</p><p>لیکوال: ${b.author||'—'}</p>${b.pdfUrl?`<a href="${b.pdfUrl}" target="_blank">PDF پرانیزه</a>`:'<small>PDF لا نه دی نښلول شوی</small>'}</div>`).join(''):'تر اوسه کتاب نشته.'}
async function access(id){try{let d=await api('/api/courses/'+id+'/access');alert('لیدل: هو\nDownload: '+(d.canDownload?'هو':'نه')+'\n\nد ویډیو اصلي Storage/Streaming به وروسته نښلوو.')}catch(e){alert(e.message)}}
$('#reg').onsubmit=async e=>{e.preventDefault();try{let d=await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert(d.message);e.target.reset();show('login')}catch(x){alert(x.message)}};
$('#log').onsubmit=async e=>{e.preventDefault();try{let d=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});tok=d.token;localStorage.zd=tok;alert('Login بریالی شو');await me();show('account')}catch(x){alert(x.message)}};
async function me(){try{let d=await api('/api/me');if(d.user.role==='admin')$('#an').classList.remove('hide')}catch{}};
async function account(){if(!tok){$('#accountBox').innerHTML='Login وکړئ.';return}try{let d=await api('/api/me'),u=d.user;$('#accountBox').innerHTML=`<h3>${u.name}</h3><p>نقش: <b>${u.role}</b></p><p>Status: <b>${u.status}</b></p><p>Faculty: ${u.faculty||'—'}</p><p>University: ${u.university||'—'}</p><button onclick="tok='';localStorage.removeItem('zd');location.reload()">Logout</button>`}catch{$('#accountBox').innerHTML='Login وکړئ.'}}
async function admin(){try{let s=await api('/api/admin/dashboard');$('#stats').innerHTML=`<div class="card">👨‍🎓 محصلان: <b>${s.students}</b></div><div class="card">👨‍🏫 استادان: <b>${s.teachers}</b></div><div class="card">⏳ Pending: <b>${s.pending}</b></div><div class="card">🎥 کورسونه: <b>${s.courses}</b></div><div class="card">📚 کتابونه: <b>${s.books}</b></div>`;let d=await api('/api/admin/users');$('#users').innerHTML=d.users.map(u=>`<div style="padding:10px;border-bottom:1px solid #ddd"><b>${u.name}</b> — ${u.role} — ${u.faculty||'—'} — ${u.status}<br>${u.role!=='admin'?`<button onclick="status('${u.id}','verified')">Verify</button> <button onclick="status('${u.id}','rejected')">Reject</button>`:''}</div>`).join('')}catch(e){alert(e.message)}}
async function status(id,s){await api('/api/admin/users/'+id+'/status',{method:'POST',body:JSON.stringify({status:s})});admin()}
$('#cfm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.downloadable=e.target.downloadable.checked;try{await api('/api/admin/courses',{method:'POST',body:JSON.stringify(o)});alert('کورس اضافه شو');e.target.reset();admin()}catch(x){alert(x.message)}};
$('#bf').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/books',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert('کتاب اضافه شو');e.target.reset();admin()}catch(x){alert(x.message)}};
me();loadCourses();
