const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,DB=path.join(__dirname,'data.json');
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
const H=s=>crypto.createHash('sha256').update(String(s)).digest('hex'),T=()=>crypto.randomBytes(12).toString('hex');
function db(){if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[{id:'admin',name:'System Admin',email:'admin@zdakrhyal.local',phone:'',password:H('Admin123!'),role:'admin',status:'verified',faculty:''}],courses:[{id:'c1',title:'د طب مقدماتي کورس',faculty:'طب',department:'عمومي طب',price:1500,downloadable:true,teacher:'Verified Teacher',description:'د طب بنسټیز ویډیو درسونه',lessons:12,videoUrl:'',bookUrl:''}],books:[]},null,2));return JSON.parse(fs.readFileSync(DB))}
const save=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2));const sessions=new Map();
function auth(req,res,next){let t=(req.headers.authorization||'').replace('Bearer ','');let s=sessions.get(t),d=db(),u=s&&d.users.find(x=>x.id===s.id);if(!u)return res.status(401).json({error:'Login required'});req.user=u;next()}
function adm(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
app.post('/api/register',(q,r)=>{let x=q.body,d=db();if(!x.name||!x.password||(!x.email&&!x.phone)||!x.faculty)return r.status(400).json({error:'نوم، Email/موبایل، Password او Faculty ضروري دي'});if(d.users.some(u=>(x.email&&u.email===x.email)||(x.phone&&u.phone===x.phone)))return r.status(409).json({error:'حساب مخکې ثبت شوی'});let u={id:'u-'+T(),name:x.name,email:x.email||'',phone:x.phone||'',password:H(x.password),role:x.role==='teacher'?'teacher':'student',status:'pending',university:x.university||'',faculty:x.faculty,department:x.department||'',semester:x.semester||'',credentials:x.credentials||''};d.users.push(u);save(d);r.json({message:'حساب جوړ شو؛ د Admin تأیید ته انتظار وکړئ'})});
app.post('/api/login',(q,r)=>{let x=q.body,d=db(),u=d.users.find(u=>(u.email===x.identifier||u.phone===x.identifier)&&u.password===H(x.password));if(!u)return r.status(401).json({error:'Login معلومات ناسم دي'});let t=T();sessions.set(t,{id:u.id});let safe={...u};delete safe.password;r.json({token:t,user:safe})});
app.get('/api/me',auth,(q,r)=>{let u={...q.user};delete u.password;r.json({user:u})});
app.get('/api/courses',auth,(q,r)=>{let d=db(),f=q.query.faculty,u=q.user; if(u.status!=='verified')return r.status(403).json({error:'ستا حساب لا تایید شوی نه دی'}); let max=Number(u.semester)||0; let courses=d.courses.filter(c=>(!f||c.faculty===f)&&(u.role==='admin'||(c.faculty===u.faculty&&(!c.department||c.department===u.department)&&Number(c.semester||1)<=max))); r.json({courses})});
app.get('/api/books',auth,(q,r)=>{let u=q.user;if(u.status!=='verified')return r.status(403).json({error:'ستا حساب لا تایید شوی نه دی'});let max=Number(u.semester)||0;let books=db().books.filter(b=>u.role==='admin'||(b.faculty===u.faculty&&(!b.department||b.department===u.department)&&Number(b.semester||1)<=max));r.json({books})});
app.get('/api/courses/:id/access',auth,(q,r)=>{let c=db().courses.find(x=>x.id===q.params.id);if(!c)return r.status(404).json({error:'Course not found'});if(q.user.status!=='verified')return r.status(403).json({error:'ستاسې Account لا نه دی تأیید شوی'});if(q.user.role!=='admin'&&(q.user.faculty!==c.faculty||(c.department&&q.user.department!==c.department)||Number(c.semester||1)>Number(q.user.semester||0)))return r.status(403).json({error:'دا کورس ستاسې د رشتې یا سمستر لپاره اجازه نه لري'});r.json({canView:true,canDownload:!!(c.downloadable&&q.user.role==='admin'||c.downloadable&&q.user.faculty===c.faculty),course:c})});
app.get('/api/admin/dashboard',auth,adm,(q,r)=>{let d=db();r.json({students:d.users.filter(x=>x.role==='student').length,teachers:d.users.filter(x=>x.role==='teacher').length,pending:d.users.filter(x=>x.status==='pending').length,courses:d.courses.length,books:d.books.length})});
app.get('/api/admin/users',auth,adm,(q,r)=>r.json({users:db().users.map(u=>{let x={...u};delete x.password;return x})}));
app.post('/api/admin/users/:id/status',auth,adm,(q,r)=>{let d=db(),u=d.users.find(x=>x.id===q.params.id);if(!u)return r.status(404).json({error:'Not found'});if(!['pending','verified','rejected'].includes(q.body.status))return r.status(400).json({error:'Invalid status'});u.status=q.body.status;save(d);r.json({message:'Updated'})});
app.post('/api/admin/courses',auth,adm,(q,r)=>{let x=q.body,d=db();if(!x.title||!x.faculty)return r.status(400).json({error:'کورس نوم او Faculty ضروري دي'});let c={id:'c-'+T(),title:x.title,faculty:x.faculty,department:x.department||'',semester:+x.semester||1,price:+x.price||0,downloadable:!!x.downloadable,teacher:x.teacher||'Verified Teacher',description:x.description||'',lessons:+x.lessons||0,videoUrl:x.videoUrl||'',bookUrl:x.bookUrl||''};d.courses.push(c);save(d);r.json({course:c})});
app.post('/api/admin/books',auth,adm,(q,r)=>{let x=q.body,d=db();if(!x.title||!x.faculty)return r.status(400).json({error:'کتاب نوم او Faculty ضروري دي'});let b={id:'b-'+T(),title:x.title,faculty:x.faculty,author:x.author||'',description:x.description||'',pdfUrl:x.pdfUrl||''};d.books.push(b);save(d);r.json({book:b})});
app.delete('/api/admin/courses/:id',auth,adm,(q,r)=>{let d=db();d.courses=d.courses.filter(x=>x.id!==q.params.id);save(d);r.json({message:'Deleted'})});
app.delete('/api/admin/books/:id',auth,adm,(q,r)=>{let d=db();d.books=d.books.filter(x=>x.id!==q.params.id);save(d);r.json({message:'Deleted'})});
app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('زدکړیال: http://localhost:'+PORT));
