-- زدکړیال Production Database Schema for Supabase/PostgreSQL
-- IMPORTANT: This schema creates the database structure. The current V10 demo server still uses data.json.
-- After running this SQL, server.js must be migrated to use Supabase/PostgreSQL.

create extension if not exists pgcrypto;

do $$ begin create type public.user_role as enum ('student','teacher','admin','superadmin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.account_status as enum ('pending','verified','rejected','suspended','blocked'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('pending','paid','rejected','refunded'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  father_name text,
  phone text unique,
  email text unique,
  role public.user_role not null default 'student',
  status public.account_status not null default 'pending',
  student_code text unique,
  university_id bigint,
  faculty_id bigint,
  department_id bigint,
  semester_id bigint,
  academic_year_id bigint,
  phone_verified boolean not null default false,
  terms_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.faculties (
  id bigint generated by default as identity primary key,
  university_id bigint references public.universities(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  unique(university_id,name)
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  faculty_id bigint not null references public.faculties(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  unique(faculty_id,name)
);

create table if not exists public.academic_years (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true
);

create table if not exists public.semesters (
  id bigint generated by default as identity primary key,
  department_id bigint references public.departments(id) on delete cascade,
  semester_no integer not null check (semester_no > 0),
  name text,
  active boolean not null default true,
  unique(department_id,semester_no)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  department_id bigint not null references public.departments(id) on delete cascade,
  semester_id bigint references public.semesters(id) on delete set null,
  name text not null,
  code text,
  active boolean not null default true
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname='profiles_university_fk') then alter table public.profiles add constraint profiles_university_fk foreign key (university_id) references public.universities(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_faculty_fk') then alter table public.profiles add constraint profiles_faculty_fk foreign key (faculty_id) references public.faculties(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_department_fk') then alter table public.profiles add constraint profiles_department_fk foreign key (department_id) references public.departments(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_semester_fk') then alter table public.profiles add constraint profiles_semester_fk foreign key (semester_id) references public.semesters(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_academic_year_fk') then alter table public.profiles add constraint profiles_academic_year_fk foreign key (academic_year_id) references public.academic_years(id) on delete set null; end if;
end $$;

create table if not exists public.teacher_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  professional_field text,
  credentials text,
  verification_notes text,
  verified_at timestamptz
);

create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete cascade,
  permission_key text not null,
  unique(admin_id,permission_key)
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  teacher_id uuid references public.profiles(id) on delete set null,
  faculty_id bigint references public.faculties(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_id bigint references public.semesters(id) on delete set null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  price numeric(12,2) not null default 0,
  thumbnail_url text,
  approved boolean not null default false,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text,
  storage_path text,
  video_url text,
  mime_type text,
  duration_seconds integer,
  price numeric(12,2) not null default 0,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  description text,
  teacher_id uuid references public.profiles(id) on delete set null,
  faculty_id bigint references public.faculties(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_id bigint references public.semesters(id) on delete set null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  storage_path text,
  price numeric(12,2) not null default 0,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.live_classes (
  id bigint generated by default as identity primary key,
  title text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  faculty_id bigint references public.faculties(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_id bigint references public.semesters(id) on delete set null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  scheduled_at timestamptz,
  meeting_url text,
  price numeric(12,2) not null default 0,
  status text not null default 'scheduled',
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  status text not null default 'active',
  enrolled_at timestamptz not null default now(),
  unique(student_id,course_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  video_id bigint references public.videos(id) on delete set null,
  book_id bigint references public.books(id) on delete set null,
  live_class_id bigint references public.live_classes(id) on delete set null,
  amount numeric(12,2) not null default 0,
  status public.order_status not null default 'pending',
  payment_method text,
  payment_reference text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  course_id bigint references public.courses(id) on delete set null,
  video_id bigint references public.videos(id) on delete set null,
  book_id bigint references public.books(id) on delete set null,
  live_class_id bigint references public.live_classes(id) on delete set null,
  amount numeric(12,2) not null default 0,
  purchased_at timestamptz not null default now()
);

create table if not exists public.video_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  seconds_watched integer not null default 0,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(student_id,video_id)
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(student_id,video_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint references public.videos(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  body text not null check (length(body) <= 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint references public.videos(id) on delete cascade,
  book_id bigint references public.books(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_token_hash text not null unique,
  device_id text,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.phone_verification_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  code_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  code_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  pass_percent numeric(5,2) default 60,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text
);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  score numeric(5,2) not null,
  passed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  certificate_no text not null unique,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  issued_at timestamptz not null default now()
);

create index if not exists idx_profiles_academic on public.profiles(university_id,faculty_id,department_id,semester_id,academic_year_id);
create index if not exists idx_profiles_role_status on public.profiles(role,status);
create index if not exists idx_courses_academic on public.courses(faculty_id,department_id,semester_id,academic_year_id);
create index if not exists idx_videos_course on public.videos(course_id);
create index if not exists idx_orders_student on public.orders(student_id,status);
create index if not exists idx_notifications_user on public.notifications(user_id,is_read);

-- Student count report: this query gives counts by university/faculty/department/semester/year.
create or replace view public.student_counts_by_academic as
select
  u.name as university,
  f.name as faculty,
  d.name as department,
  s.semester_no,
  ay.name as academic_year,
  count(p.id)::bigint as student_count
from public.profiles p
left join public.universities u on u.id=p.university_id
left join public.faculties f on f.id=p.faculty_id
left join public.departments d on d.id=p.department_id
left join public.semesters s on s.id=p.semester_id
left join public.academic_years ay on ay.id=p.academic_year_id
where p.role='student'
group by u.name,f.name,d.name,s.semester_no,ay.name;

-- Admin helper: Super Admin is the only role allowed to create/change admin permissions in the application.
-- The application server should use the Supabase service role for trusted admin operations.

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.videos enable row level security;
alter table public.books enable row level security;
alter table public.live_classes enable row level security;
alter table public.notifications enable row level security;
alter table public.orders enable row level security;
alter table public.purchases enable row level security;
alter table public.video_progress enable row level security;

-- Basic policies for student self-service. Keep privileged writes on the server using service role.
drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select using (id=auth.uid());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists notifications_self_select on public.notifications;
create policy notifications_self_select on public.notifications for select using (user_id=auth.uid());

drop policy if exists orders_self_select on public.orders;
create policy orders_self_select on public.orders for select using (student_id=auth.uid());

drop policy if exists purchases_self_select on public.purchases;
create policy purchases_self_select on public.purchases for select using (student_id=auth.uid());

drop policy if exists progress_self_all on public.video_progress;
create policy progress_self_all on public.video_progress for all using (student_id=auth.uid()) with check (student_id=auth.uid());

-- Public catalog read policies can be narrowed later according to approval/publishing rules.
drop policy if exists courses_public_read on public.courses;
create policy courses_public_read on public.courses for select using (published=true and approved=true);

drop policy if exists videos_public_read on public.videos;
create policy videos_public_read on public.videos for select using (exists(select 1 from public.courses c where c.id=course_id and c.published=true and c.approved=true));

-- IMPORTANT SECURITY NOTE:
-- Do NOT put SUPABASE_SERVICE_ROLE_KEY in browser JavaScript. Keep it only on the server/environment variables.

-- ================================================================
-- Production additions: study-start, official semester lifecycle,
-- attendance, receipts, ads, footer/site controls, audit logs.
-- ================================================================

alter table public.profiles add column if not exists study_start_date date;
alter table public.profiles add column if not exists calculated_semester_no integer check (calculated_semester_no is null or calculated_semester_no > 0);
alter table public.profiles add column if not exists official_semester_no integer check (official_semester_no is null or official_semester_no > 0);
alter table public.profiles add column if not exists university_verified_at timestamptz;
alter table public.profiles add column if not exists verified_by uuid references public.profiles(id) on delete set null;

create table if not exists public.program_semester_limits (
  department_id bigint primary key references public.departments(id) on delete cascade,
  max_semesters integer not null check (max_semesters > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.official_semesters (
  id bigint generated by default as identity primary key,
  university_id bigint references public.universities(id) on delete cascade,
  faculty_id bigint references public.faculties(id) on delete cascade,
  department_id bigint references public.departments(id) on delete cascade,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  semester_no integer not null check (semester_no > 0),
  name text,
  starts_on date not null,
  ends_on date,
  status text not null default 'planned' check (status in ('planned','active','locked','completed')),
  started_by uuid references public.profiles(id) on delete set null,
  started_at timestamptz,
  locked_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists official_semesters_scope_idx on public.official_semesters(university_id,faculty_id,department_id,semester_no,status);

create table if not exists public.semester_history (
  id bigint generated by default as identity primary key,
  official_semester_id bigint references public.official_semesters(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_no integer not null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  started_at timestamptz,
  ended_at timestamptz,
  locked_at timestamptz,
  locked_by uuid references public.profiles(id) on delete set null,
  notes text
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  live_class_id bigint not null references public.live_classes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'absent' check (status in ('absent','present','late','excused')),
  joined_at timestamptz,
  left_at timestamptz,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  corrected_manually boolean not null default false,
  corrected_by uuid references public.profiles(id) on delete set null,
  corrected_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  unique(live_class_id,student_id)
);
create index if not exists attendance_student_idx on public.attendance(student_id,created_at desc);

create table if not exists public.payment_receipts (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  storage_path text not null,
  original_name text,
  mime_type text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text,
  target_url text,
  position text not null default 'home' check (position in ('home','header','footer','sidebar','course')),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  target_university_id bigint references public.universities(id) on delete set null,
  target_faculty_id bigint references public.faculties(id) on delete set null,
  target_department_id bigint references public.departments(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id boolean primary key default true check (id),
  platform_name text not null default 'زدکړیال',
  hero_image_url text,
  footer_creator_name text,
  footer_creator_email text,
  footer_creator_photo_url text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.site_settings(id) values(true) on conflict(id) do nothing;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);

create or replace function public.semester_from_start_date(start_date date, as_of date default current_date)
returns integer
language sql immutable
as $$
  select case when start_date is null or as_of < start_date then null
              else floor(extract(epoch from (as_of::timestamp - start_date::timestamp)) / (86400 * 30.4375 * 6))::integer + 1
         end;
$$;

create or replace function public.refresh_calculated_semester(p_user uuid)
returns integer
language plpgsql
security definer
as $$
declare s integer; lim integer;
begin
  select public.semester_from_start_date(study_start_date,current_date) into s from public.profiles where id=p_user;
  select max_semesters into lim from public.program_semester_limits l join public.profiles p on p.department_id=l.department_id where p.id=p_user;
  if s is not null and lim is not null and s > lim then s := lim; end if;
  update public.profiles set calculated_semester_no=s, updated_at=now() where id=p_user;
  return s;
end;
$$;

-- Helper: only a verified student can access content matching the same university/faculty/department
-- and semester <= the student's official/current eligible semester.
create or replace function public.student_can_access(
  p_student uuid,
  p_university bigint,
  p_faculty bigint,
  p_department bigint,
  p_semester integer
) returns boolean
language sql stable security definer
as $$
  select exists (
    select 1 from public.profiles p
    where p.id=p_student
      and p.role='student'
      and p.status='verified'
      and (p_university is null or p.university_id=p_university)
      and (p_faculty is null or p.faculty_id=p_faculty)
      and (p_department is null or p.department_id=p_department)
      and (p_semester is null or p_semester <= coalesce(p.official_semester_no,p.calculated_semester_no,0))
  );
$$;

-- RLS: default deny, then allow safe student self-service and public catalog reads.
alter table public.profiles enable row level security;
alter table public.universities enable row level security;
alter table public.faculties enable row level security;
alter table public.departments enable row level security;
alter table public.academic_years enable row level security;
alter table public.semesters enable row level security;
alter table public.subjects enable row level security;
alter table public.notifications enable row level security;
alter table public.attendance enable row level security;
alter table public.official_semesters enable row level security;
alter table public.site_settings enable row level security;
alter table public.ads enable row level security;

-- Public academic catalog.
drop policy if exists universities_public_read on public.universities;
create policy universities_public_read on public.universities for select using (active=true);
drop policy if exists faculties_public_read on public.faculties;
create policy faculties_public_read on public.faculties for select using (active=true);
drop policy if exists departments_public_read on public.departments;
create policy departments_public_read on public.departments for select using (active=true);
drop policy if exists academic_years_public_read on public.academic_years;
create policy academic_years_public_read on public.academic_years for select using (active=true);

-- Student may read own profile only.
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated using (id=auth.uid());
-- Profile changes are performed by the trusted server API so students cannot alter role/status/university/faculty.

-- Notifications are private to the owner.
drop policy if exists notifications_self_read on public.notifications;
create policy notifications_self_read on public.notifications for select to authenticated using (user_id=auth.uid());
drop policy if exists notifications_self_update on public.notifications;
create policy notifications_self_update on public.notifications for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

-- Attendance: student reads own attendance. Admin/service role can manage.
drop policy if exists attendance_self_read on public.attendance;
create policy attendance_self_read on public.attendance for select to authenticated using (student_id=auth.uid());

-- Site settings and active ads are public-readable.
drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings for select using (true);
drop policy if exists ads_public_read on public.ads;
create policy ads_public_read on public.ads for select using (active=true and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now()));

-- Important: service_role bypasses RLS and is used only from server-side API routes.
