-- زدکړیال Production Database Schema for Supabase/PostgreSQL
-- IMPORTANT: This schema creates the database structure. The current V10 demo server still uses data.json.
-- After running this SQL, server.js must be migrated to use Supabase/PostgreSQL.

create extension if not exists pgcrypto;

do $$ begin create type public.user_role as enum ('student','teacher','admin','superadmin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.account_status as enum ('pending','verified','rejected','suspended','blocked'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('pending','paid','rejected','refunded'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  father_name text,
  phone text unique,
  email text unique,
  role public.user_role not null default 'student',
  status public.account_status not null default 'pending',
  student_code text unique,
  university_id bigint,
  faculty_id bigint,
  department_id bigint,
  semester_id bigint,
  academic_year_id bigint,
  phone_verified boolean not null default false,
  terms_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.faculties (
  id bigint generated by default as identity primary key,
  university_id bigint references public.universities(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  unique(university_id,name)
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  faculty_id bigint not null references public.faculties(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  unique(faculty_id,name)
);

create table if not exists public.academic_years (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true
);

create table if not exists public.semesters (
  id bigint generated by default as identity primary key,
  department_id bigint references public.departments(id) on delete cascade,
  semester_no integer not null check (semester_no > 0),
  name text,
  active boolean not null default true,
  unique(department_id,semester_no)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  department_id bigint not null references public.departments(id) on delete cascade,
  semester_id bigint references public.semesters(id) on delete set null,
  name text not null,
  code text,
  active boolean not null default true
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname='profiles_university_fk') then alter table public.profiles add constraint profiles_university_fk foreign key (university_id) references public.universities(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_faculty_fk') then alter table public.profiles add constraint profiles_faculty_fk foreign key (faculty_id) references public.faculties(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_department_fk') then alter table public.profiles add constraint profiles_department_fk foreign key (department_id) references public.departments(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_semester_fk') then alter table public.profiles add constraint profiles_semester_fk foreign key (semester_id) references public.semesters(id) on delete set null; end if;
  if not exists (select 1 from pg_constraint where conname='profiles_academic_year_fk') then alter table public.profiles add constraint profiles_academic_year_fk foreign key (academic_year_id) references public.academic_years(id) on delete set null; end if;
end $$;

create table if not exists public.teacher_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  professional_field text,
  credentials text,
  verification_notes text,
  verified_at timestamptz
);

create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete cascade,
  permission_key text not null,
  unique(admin_id,permission_key)
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  teacher_id uuid references public.profiles(id) on delete set null,
  faculty_id bigint references public.faculties(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_id bigint references public.semesters(id) on delete set null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  price numeric(12,2) not null default 0,
  thumbnail_url text,
  approved boolean not null default false,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text,
  storage_path text,
  video_url text,
  mime_type text,
  duration_seconds integer,
  price numeric(12,2) not null default 0,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  description text,
  teacher_id uuid references public.profiles(id) on delete set null,
  faculty_id bigint references public.faculties(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_id bigint references public.semesters(id) on delete set null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  storage_path text,
  price numeric(12,2) not null default 0,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.live_classes (
  id bigint generated by default as identity primary key,
  title text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  faculty_id bigint references public.faculties(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  semester_id bigint references public.semesters(id) on delete set null,
  academic_year_id bigint references public.academic_years(id) on delete set null,
  scheduled_at timestamptz,
  meeting_url text,
  price numeric(12,2) not null default 0,
  status text not null default 'scheduled',
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  status text not null default 'active',
  enrolled_at timestamptz not null default now(),
  unique(student_id,course_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  video_id bigint references public.videos(id) on delete set null,
  book_id bigint references public.books(id) on delete set null,
  live_class_id bigint references public.live_classes(id) on delete set null,
  amount numeric(12,2) not null default 0,
  status public.order_status not null default 'pending',
  payment_method text,
  payment_reference text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  course_id bigint references public.courses(id) on delete set null,
  video_id bigint references public.videos(id) on delete set null,
  book_id bigint references public.books(id) on delete set null,
  live_class_id bigint references public.live_classes(id) on delete set null,
  amount numeric(12,2) not null default 0,
  purchased_at timestamptz not null default now()
);

create table if not exists public.video_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  seconds_watched integer not null default 0,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(student_id,video_id)
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(student_id,video_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint references public.videos(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  body text not null check (length(body) <= 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  video_id bigint references public.videos(id) on delete cascade,
  book_id bigint references public.books(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_token_hash text not null unique,
  device_id text,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.phone_verification_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  code_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  code_hash text not null,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  pass_percent numeric(5,2) default 60,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text
);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  score numeric(5,2) not null,
  passed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  certificate_no text not null unique,
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  issued_at timestamptz not null default now()
);

create index if not exists idx_profiles_academic on public.profiles(university_id,faculty_id,department_id,semester_id,academic_year_id);
create index if not exists idx_profiles_role_status on public.profiles(role,status);
create index if not exists idx_courses_academic on public.courses(faculty_id,department_id,semester_id,academic_year_id);
create index if not exists idx_videos_course on public.videos(course_id);
create index if not exists idx_orders_student on public.orders(student_id,status);
create index if not exists idx_notifications_user on public.notifications(user_id,is_read);

-- Student count report: this query gives counts by university/faculty/department/semester/year.
create or replace view public.student_counts_by_academic as
select
  u.name as university,
  f.name as faculty,
  d.name as department,
  s.semester_no,
  ay.name as academic_year,
  count(p.id)::bigint as student_count
from public.profiles p
left join public.universities u on u.id=p.university_id
left join public.faculties f on f.id=p.faculty_id
left join public.departments d on d.id=p.department_id
left join public.semesters s on s.id=p.semester_id
left join public.academic_years ay on ay.id=p.academic_year_id
where p.role='student'
group by u.name,f.name,d.name,s.semester_no,ay.name;

-- Admin helper: Super Admin is the only role allowed to create/change admin permissions in the application.
-- The application server should use the Supabase service role for trusted admin operations.

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.videos enable row level security;
alter table public.books enable row level security;
alter table public.live_classes enable row level security;
alter table public.notifications enable row level security;
alter table public.orders enable row level security;
alter table public.purchases enable row level security;
alter table public.video_progress enable row level security;

-- Basic policies for student self-service. Keep privileged writes on the server using service role.
drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select using (id=auth.uid());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists notifications_self_select on public.notifications;
create policy notifications_self_select on public.notifications for select using (user_id=auth.uid());

drop policy if exists orders_self_select on public.orders;
create policy orders_self_select on public.orders for select using (student_id=auth.uid());

drop policy if exists purchases_self_select on public.purchases;
create policy purchases_self_select on public.purchases for select using (student_id=auth.uid());

drop policy if exists progress_self_all on public.video_progress;
create policy progress_self_all on public.video_progress for all using (student_id=auth.uid()) with check (student_id=auth.uid());

-- Public catalog read policies can be narrowed later according to approval/publishing rules.
drop policy if exists courses_public_read on public.courses;
create policy courses_public_read on public.courses for select using (published=true and approved=true);

drop policy if exists videos_public_read on public.videos;
create policy videos_public_read on public.videos for select using (exists(select 1 from public.courses c where c.id=course_id and c.published=true and c.approved=true));

-- IMPORTANT SECURITY NOTE:
-- Do NOT put SUPABASE_SERVICE_ROLE_KEY in browser JavaScript. Keep it only on the server/environment variables.
